meta:
  name: "BODY / Thực thi hệ thống"
  version: "1.7.7"
  chg_id: "2025-08-17T16:24:08.946067+00:00"
  description: "Chế độ an toàn, reconcile, circuit-breaker, degrade."
  owners: ["you@example.com"]
  timezone: "Asia/Bangkok"

modes:
  cold_start: "WAIT"
  maintenance_window:
    enabled: true
    schedule: ["Sat 00:00-02:00"]
  pause_flag_file: "reload.flag"

reconcile:
  interval_seconds: 60
  full_reconcile_on_start: true

circuit_breakers:
  max_drawdown_day_pct: 4.0
  max_consecutive_losses: 5
  max_latency_ms: 2500
  on_trigger: ["pause_new","reduce_only"]

degrade_modes:
  network_slow: "reduce_only"
  data_partial: "hold_new_orders"

healthchecks:
  exchange_latency_ms_warn: 1200
  telegram_ping_fail_warn: 2

telemetry:
  slo:
    executor_p95_ms: 900
    api_p95_ms: 300
