meta:
  name: "BODY"
  version: "1.7.7"
  chg_id: "Fix-2025-09-08"
  description: "Cấu hình BODY cho Phase B."

modes:
  normal:
    enabled: true
  maintenance_window: {}

reconcile:
  enabled: true
  interval_sec: 60

circuit_breakers:
  trading_halt_on_error: true
  max_consecutive_errors: 3
  cooldown_after_halt_sec: 300

degrade_modes:
  safe_mode: false
  network_slow: reduce_only      # ← bắt buộc: literal
  data_partial: hold_new_orders  # ← bắt buộc: literal

healthchecks:
  enabled: true
  interval_sec: 60

telemetry:
  logging_level: "info"
  slo: {}

time_sync:
  max_clock_skew_ms: 500