controller:
  allowed_routes: ["LEFT", "RIGHT", "WAIT"]   # Phase B: tắt BOTH
  inherit_safe_mode_from_right: true          # Right có quyền hãm
  cooldown_switch_seconds: 15                 # chống rung
  max_route_flips_per_hour: 8                 # 8–10/h theo plan
  max_parallel_orders: 1                      # chỉ 1 lệnh song song