feature_flags:
  floors:
    open_conf_floor: 0.65       # không hạ
    close_flip_conf_floor: 0.60 # không hạ
  loop:
    minutes: 15                 # CRX_LOOP_MINUTES
    cooldown_decision_sec: 120  # CRX_COOLDOWN_DECISION_SEC